# Generated by Django 3.2.3 on 2021-06-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(default='', max_length=128, unique=True, verbose_name='유저 이메일')),
                ('user_id', models.CharField(default='', max_length=32, unique=True, verbose_name='유저 아이디')),
                ('user_pw', models.CharField(default='', max_length=128, verbose_name='유저 비밀번호')),
                ('user_name', models.CharField(default='', max_length=16, verbose_name='유저 이름')),
                ('user_birth', models.DateField(default='', verbose_name='유저 생일')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저',
                'db_table': 'user',
            },
        ),
    ]
