# Generated by Django 2.2.9 on 2021-08-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, null=True)),
                ('pick_date', models.DateField(null=True)),
                ('create_date', models.DateField(auto_now=True, null=True)),
                ('music', models.CharField(max_length=100, null=True)),
                ('mood', models.CharField(choices=[('happy', 'happy'), ('soso', 'soso'), ('sad', 'sad'), ('angry', 'angry')], max_length=5, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('lat', models.CharField(max_length=50, null=True)),
                ('lng', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
